name = input ("geef je naam")
print ("hallo" + name) 
a = input ("Adres?")
b = input ("Postcode?")
c = input ("Woonplaats?")
print ("----------------------------------------------------")
print ("Adres: " + a )
print ("Postcode: " + b)
print ("Woonplaats: " + c)
print ("----------------------------------------------------")